query Employees($where: EmployeeWhereInput, $orderBy: [EmployeeOrderByWithRelationInput!], $cursor: EmployeeWhereUniqueInput, $take: Int, $skip: Int, $distinct: [EmployeeScalarFieldEnum!]) {
  employees(where: $where, orderBy: $orderBy, cursor: $cursor, take: $take, skip: $skip, distinct: $distinct) {
    id
    image
    name
    role
    shortDescription
  }
}

mutation CreateOneEmployee($data: EmployeeCreateInput!) {
  createOneEmployee(data: $data) {
    id
  }
}

mutation UpdateOneEmployee($data: EmployeeUpdateInput!, $where: EmployeeWhereUniqueInput!) {
  updateOneEmployee(data: $data, where: $where) {
    id
  }
}